---
- name: install kakoune from latest git master
  become: true
  vars:
    kakoune_src_dir: /usr/src/kakoune
  block:
    - name: install required packages
      apt:
        name: editorconfig
        state: present
    - name: fetch source from git
      git:
        repo: https://github.com/mawww/kakoune.git
        dest: "{{ kakoune_src_dir }}"
    - name: build from source and install
      shell:
        cmd: |
          make
          make install
        chdir: "{{ kakoune_src_dir }}"
- name: populate user configuration
  vars:
    config_directory: "~/.config/kak"
  block:
    - name: ensure existence of config directory
      file:
        path: "{{ config_directory }}"
        state: directory
    - name: copy configuration file
      copy:
        src: kakrc
        dest: "{{ config_directory }}"
# TODO: Implement
# - name: install plugins
#   when: false
#   debug:
#     msg: 'no'
- name: populate kak-lsp configuration
  vars:
    config_directory: "~/.config/kak-lsp"
  block:
    - name: ensure existence of config directory
      file:
        path: "{{ config_directory }}"
        state: directory
    - name: copy configuration file
      copy:
        src: kak-lsp.toml
        dest: "{{ config_directory }}"
