---
- name: install kakoune from latest git master
  become: true
  vars:
    kakoune_src_dir: /usr/src/kakoune
  block:
    - name: install required packages
      apt:
        name:
          - editorconfig
        state: latest

    - name: fetch source from git
      git:
        repo: https://github.com/mawww/kakoune.git
        dest: "{{ kakoune_src_dir }}"

    - name: build from source and install
      shell:
        cmd: |
          make
          make install
        chdir: "{{ kakoune_src_dir }}"

- name: populate user configuration
  copy:
    src: kakrc
    dest: ~/.config/kakrc

- name: install plugins
  when: false
