#
# Configure Plug.kak and plugins
#

# Idempotent install script
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

# Register but don't load plugin manager (prevents deletion when cleaning)
plug "andreyorst/plug.kak" noload

# Register and load my plugins
plug "andreyorst/fzf.kak"
plug "alexherbo2/surround.kak"
plug "jcuffe/auto-pairs.kak" branch "maintain-append-selection"
plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
}

#
# Options and Settings
#

# Always reload files that have changed on disk
set-option global autoreload true

# Always show number lines
add-highlighter global/ number-lines

#
# LSP
#

# Enable LSP integration
lsp-enable

# Add User mode shortcuts
map global user r ': lsp-rename-prompt<ret>'
map global user h ': lsp-hover<ret>'

#
# Mappings
#

# Enter surround mode
map -docstring 'surround mode' global normal q ': enter-surround-mode<ret>'

# Format document
map -docstring 'format document' global user f ': format<ret>'

# Comment command
map -docstring 'comment line(s)' global user c ': comment-line<ret>'
map -docstring 'comment block' global user C ': comment-block<ret>'

# Split windows
map -docstring 'split editor (vertical)' global user \" ':tmux-terminal-vertical kak -c %val{session}<ret>'
map -docstring 'split editor (horizontal)' global user \% ':tmux-terminal-horizontal kak -c %val{session}<ret>'

#
# Hooks
#

# Yank to the system clipboard (`y` only)
hook global NormalKey y %{
    nop %sh{
        # Set contents of main register to tmux copy buffer
        # -w flag is required to pass data along to system clipboard
        tmux setb -w "$kak_main_reg_dquote"

        # Currently using tmux instead of OSC 52
        # Emit OSC 52 escape sequence with the yanked text as argument
        # encoded=$(printf %s "$kak_main_reg_dquote" | base64 | tr -d '\n')
        # printf "\e]52;c;%s\e\\" "$encoded" > /dev/tty
    }
}

# Configure IDE services for all languages
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    # Load editorconfig
    editorconfig-load
}

# Format JS/TS with Prettier
hook global BufSetOption filetype=(typescript|javascript) %{
    set-option buffer formatcmd "prettier --stdin-filepath=%val{buffile}"
}

# Format YAML with yq
hook global BufSetOption filetype=(yaml) %{
    set-option buffer formatcmd "yq < %val{buffile}"
}
